### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by coolman911099** [conradev/webn.es#8] opened 2019-02-23 04:24 UTC
![screenshot_2019-02-22-23-27-23](https://user-images.githubusercontent.com/47460199/53281622-a7b62700-36f9-11e9-88db-b87469302717.png)
On any web browser I use I can't get any thing to work just lodes webn.es with the top bar showing up and that it when I.but the plus to go to Dropbox nothing happens at all

**Comment by HTV04** [comment] 2019-09-16 20:26
Don't mean to plug or anything, but I made a fork of webNES that fixes these issues: https://github.com/HTV04/htv04.github.io/tree/master/webnes-ce

So far it only seems to be working as intended on Android, so this should address your issue. Can't say the same about iOS (which is what I mainly use), lol.

**Comment by conradev** [comment] 2022-04-10 18:23
Closing as a duplicate of #13

**Closed by conradev** 2022-04-10 18:23 UTC
